name: mdl
version: "0.4.0"
summary: Markdown lint tool
description: |
  A tool to check markdown files and flag style issues.
  Usage: mdl file or cat file | mdl
grade: stable
confinement: strict

apps:
  mdl:
    command: mdl
    plugs: [home, removable-media]

parts:
  mdl.rb:
    source: https://github.com/markdownlint/markdownlint.git
    source-tag: v0.4.0
    plugin: ruby
    build: gem build mdl.gemspec
    install: gem install mdl-*.gem --env-shebang
