name: mdl
version: 'master'
version-script: git -C parts/mdl/build describe --tags
summary: Markdown lint tool
description: |
  A tool to check markdown files and flag style issues.
  Usage: mdl file or cat file | mdl
grade: stable
confinement: strict

apps:
  mdl:
    command: mdl
    plugs: [home, removable-media]

parts:
  mdl.rb:
    source: https://github.com/markdownlint/markdownlint.git
    plugin: ruby
    override-build: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info mdl | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      gem build mdl.gemspec
      gem install mdl-*.gem --env-shebang
